config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  root to: "home#index"

  #ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
    member do
      get :following, :followers
    end
    collection do
      get :favorite_cs
      get :favorite_sitters
    end
  end
  
  resources :post_c do
    resource :favorite_cs, only: [:create, :destroy]
  end

  delete 'post_c/:id', to: 'post_c#destroy'

  resources :post_sitter do
    resource :favorite_sitters, only: [:create, :destroy]
  end

  delete 'post_sitter/:id', to: 'post_sitter#destroy'

  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  get "show_additionally", to: "rooms#show_additionally"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'
end

app/models/post_sitter.rb
class PostSitter < ApplicationRecord
  #投稿時期が早いものから順に表示
  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :region, presence: true
  validates :datetime, presence: true
  validates :price, presence: true
  validates :payment, presence: true
  validates :content, presence: true

  belongs_to :user
  
  has_many :favorite_sitters, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  mount_uploader :image, ImageUploader
  
  def create_notification_favorite_sitter!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_sitter_id = ? and action = ? ", current_user.id, user_id, id, 'favorite_sitter'])

    if temp.blank?
      notification = current_user.active_notifications.new(
        post_sitter_id: id,
        visited_id: user_id,
        action: 'favorite_sitter'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
end

app/controllers/post_sitter_controller.rb
class PostSitterController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = PostSitter.all
  end

  def show
    @post = PostSitter.find(params[:id])
    @user = User.find(params[:id])
  end

  def new
    @post = PostSitter.new
  end

  def create
    @post = PostSitter.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_sitter_path(@post), notice: "投稿に成功しました！！"
    else
      flash[:alert] = "投稿に失敗しました！！"
      render :new
    end
  end

  def edit
    @post = PostSitter.find(params[:id])
    @post.user_id = current_user.id
    @post.save
  end

  def update
    @post = PostSitter.find(params[:id])
    if @post.update(post_params)
      redirect_to post_sitter_path(@post), notice: "投稿内容の編集に成功しました！！"
    else
      flash[:alert] = "投稿内容の編集に失敗しました！！"
      render :edit
    end
  end

  def destroy
    @post = PostSitter.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to root_path
  end

  private
  
  def post_params
    params.require(:post_sitter).permit(:title, :region, :datetime, :price, :payment, :content, :image, :remove_image)
  end

  def set_post
    @post = PostSitter.find(params[:id])
  end

end

app/helpers/post_sitter_helper.rb
module PostSitterHelper
end

app/views/post_sitter/edit.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">
    <div class="row justify-content-center">
      <div class="form-col col-md-7 col-lg-5">
        <h2 class="text-center title-color">投稿内容を編集する</h2>

        <%= form_with(model: @post, url: "/post_sitter/#{@post.id}", local: true) do |f| %>

          <div class="field field-mt">
            <%= f.label :タイトル %><span class="required">必須</span><br />
            <%= f.text_field :title, autofocus: true %>
          </div>
          
          <div type="button" class="image-btn field-mt">
            <%= f.label :画像 %><br />
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
          </div>

          <div class="field field-mt">
            <%= f.label :お住まいの地域 %><span class="required">必須</span><br />
            <%= f.text_field :region %>
          </div>

          <div class="field field-mt">
            <%= f.label :希望日時 %><span class="required">必須</span><br />
            <%= f.text_field :datetime %>
          </div>

          <div class="field field-mt">
            <%= f.label :希望料金 %><span class="required">必須</span><br />
            <%= f.text_field :price %>
          </div>

          <div class="field field-mt">
            <%= f.label :お支払い方法 %><span class="required">必須</span><br />
            <%= f.select :payment, ["現地でお支払い", "事前振り込み", "事後振り込み"], :prompt => "選択してください" %>
          </div>

          <div class="field field-mt">
            <%= f.label :リクエスト内容 %><span class="required">必須</span><br />
            <%= f.text_area :content %>
          </div>

          <div class="actions actions-mt">
            <%= f.submit "編集する" %>
          </div>
          
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/post_sitter/index.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">
    <div class="justify-content-center">
      <h2 class="text-center title-color mb-5">シッター 一覧</h2>

      <div class="post-index-wrap">
        <% @posts.each do |post| %>
          <%= link_to post_sitter_path(post.id) do %>
            <div class="media">
              <div class="icon2">
                <% if post.user.image? %>              
                  <%= image_tag post.user.image.url, size: 100, class: "media-object" %>
                <% else %>
                  <%= image_tag "/assets/default.png", size: 100 %>
                <% end %>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= post.title %></h4>
                <p class="post-index-username"><%= post.user.username %></p>
                <p><%= simple_format post.content %></p>
                <ul class="list-inline list-unstyled">
                  <li class="list-inline-item"><span><p class="mb-1">地域</p> <%= post.region %> </span></li>
                  <li class="list-inline-item">|</li>
                  <li class="list-inline-item"><span><p class="mb-1">日時</p> <%= post.datetime %> </span></li>
                  <li class="list-inline-item">|</li>
                  <li class="list-inline-item"><span><p class="mb-1">料金</p> <%= post.price %> </span></li>
                </ul>
              </div>
            </div>

          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</main>

app/views/post_sitter/new.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">
    <div class="row justify-content-center">
      <div class="form-col col-md-7 col-lg-5">
        <h2 class="text-center title-color">シッターとして投稿する</h2>

        <%= form_with(model: @post, url: "/post_sitter/#{@post.id}", local: true) do |f| %>

          <div class="field field-mt">
            <%= f.label :タイトル %><span class="required">必須</span><br />
            <%= f.text_field :title, autofocus: true %>
          </div>
          
          <div type="button" class="image-btn field-mt">
            <%= f.label :画像 %><br />
            <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
          </div>

          <div class="field field-mt">
            <%= f.label :お住まいの地域 %><span class="required">必須</span><br />
            <%= f.text_field :region %>
          </div>

          <div class="field field-mt">
            <%= f.label :希望日時 %><span class="required">必須</span><br />
            <%= f.text_field :datetime %>
          </div>

          <div class="field field-mt">
            <%= f.label :希望料金 %><span class="required">必須</span><br />
            <%= f.text_field :price %>
          </div>

          <div class="field field-mt">
            <%= f.label :お支払い方法 %><span class="required">必須</span><br />
            <%= f.select :payment, ["現地でお支払い", "事前振り込み", "事後振り込み"], :prompt => "選択してください" %>
          </div>

          <div class="field field-mt">
            <%= f.label :リクエスト内容 %><span class="required">必須</span><br />
            <%= f.text_area :content %>
          </div>

          <div class="actions actions-mt">
            <%= f.submit "投稿する" %>
          </div>
          
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/post_sitter/show.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">
    <div class="row justify-content-center">


      <div class="col-lg-4 text-center post-profile-wrap">
        <%= link_to user_path(@post.user) do %>
          <div class="icon mb-2">
            <% if @user.image? %>
              <%= image_tag @post.user.image.url, size: 160 %>
            <% else %>
              <%= image_tag "/assets/default.png", size: 160 %>
            <% end %>
          </div>
        <% end %>
        <div class="user-name mb-2">
          <h3 class="font-weight-bold"><%= @post.user.username %></h3>
        </div>
        <% if @post.user.id == current_user.id %>
          <div class="post-bt">
            <%= link_to "編集", edit_post_sitter_path(@post) %>
          </div>
          <%= button_to "投稿を削除", post_sitter_path(@post.id), class: "post-edit-delete", data: { confirm: "本当に削除しますか？" }, method: :delete %>
        <% else %>
          <div class="post-bt">
            <%= link_to "レビュー", new_user_review_path(@post.user.id) %>
          </div>
          <div class="post-bt">
            <%= link_to "レビューを見る", user_reviews_path(@post.user.id) %>
          </div>
        <% end %>
      </div>


      <div class="col-lg-8 post-text-wrap">
        <div class="post-show-inner">
          <div>
            <h2 class="post-show-title font-weight-bold text-dark text-center mb-3"><%= @post.title %></h2>
          </div>
          <div class="post-show-image text-center mb-5">
            <% if @post.image? %>
              <%= link_to @post.image.url, 'data-lightbox': @post.image do %>
                <%= image_tag @post.image.url, class: "img-fluid" %>
              <% end %>
            <% else %>
              <%= image_tag '/assets/noimage.dog1.png' %>
            <% end %>
          </div>
          <div class="favorite post-show-favorite">
            <% if @post.user.id != current_user.id %>
              <%= render "favorite_sitters/favorite", post_sitter: @post %>
            <% end %>
          </div>
          <div>
            <h5 class="post-show-title-text font-weight-bold text-dark mb-2">お住いの地域</h5>
            <p class="post-show-text mb-4"><%= @post.region %></p>
          </div>
          <div>
            <h5 class="post-show-title-text font-weight-bold text-dark mb-2">希望日時</h5>
            <p class="post-show-text mb-4"><%= @post.datetime %></p>
          </div>
          <div>
            <h5 class="post-show-title-text font-weight-bold text-dark mb-2">希望料金</h5>
            <p class="post-show-text mb-4"><%= @post.price %></p>
          </div>
          <div>
            <h5 class="post-show-title-text font-weight-bold text-dark mb-2">お支払い方法</h5>
            <p class="post-show-text mb-4"><%= @post.payment %></p>
          </div>
          <div class="post-show-comment">
            <p><%= simple_format @post.content %></p>
          </div>
        </div>
      </div>

    </div>
  </div>
</main>