config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  root to: "home#index"

  #ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
    member do
      get :following, :followers
    end
    collection do
      get :favorite_cs
      get :favorite_sitters
    end
  end
  
  resources :post_c do
    resource :favorite_cs, only: [:create, :destroy]
  end

  delete 'post_c/:id', to: 'post_c#destroy'

  resources :post_sitter do
    resource :favorite_sitters, only: [:create, :destroy]
  end

  delete 'post_sitter/:id', to: 'post_sitter#destroy'

  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  get "show_additionally", to: "rooms#show_additionally"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :post_c, optional: true
  belongs_to :post_sitter, optional: true
  belongs_to :room, optional: true
  belongs_to :message, optional: true
  belongs_to :review, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
    @visitor = notification.visitor
    @message = nil
    your_item = link_to 'あなたの投稿', room_path(notification), style: "font-weight: bold;"
    @visitor_message = notification.message_id

    case notification.action
      when 'follow' then
        tag.a(@visitor.username, href: user_path(@visitor), style: "font-weight: bold;")+"さんがあなたをフォローしました"
      when 'favorite' then
        tag.a(@visitor.username, href: user_path(@visitor), style: "font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href: post_c_path(notification.post_c_id), style: "font-weight: bold;")+"にいいねしました"
      when 'favorite_sitter' then
        tag.a(@visitor.username, href: user_path(@visitor), style: "font-weight: bold;")+"さんが"+tag.a('あなたの投稿', href: post_sitter_path(notification.post_sitter_id), style: "font-weight: bold;")+"にいいねしました"
      when 'message' then
        @message = Message.find_by(id: @visitor_message)&.content
        tag.a(@visitor.username, href: user_path(@visitor), style: "font-weight: bold;")+"さんから"+tag.a('メッセージ', href: room_path(notification.room_id), style: "font-weight: bold;")+"が届きました"
      when 'review' then
        tag.a(@visitor.username, href: user_path(@visitor), style: "font-weight: bold;")+"さんがあなたに"+tag.a('レビューしました', href: user_reviews_path(user_id: current_user.id), style: "font-weight: bold;")
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="user-view clearfix mb-3">
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br>
  <% if !@message.nil? %>
    <p class="moderate-font mt-2 mb-2" style="color: #C0C0C0;"><%= @message %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container notification">
    <div class="justify-content-center">
      <h2 class="text-center title-color mb-5">通知</h2>

      <%= link_to notifications_destroy_all_path do %>
        <div>
          <i class="fas fa-trash" style="color: black;"></i>
          <h7 style="color: black;">全削除</h7>
        </div>
      <% end %>
      <hr>
      <% if @notifications.exists? %>
        <div class="users-index">
          <%= render @notifications %>
          <%= paginate @notifications %>
        </div>
      <% else %>
        <p>通知はありません</p>
      <% end %>
      
    </div>
  </div>
</main>