config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  root to: "home#index"

  #ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
    member do
      get :following, :followers
    end
    collection do
      get :favorite_cs
      get :favorite_sitters
    end
  end
  
  resources :post_c do
    resource :favorite_cs, only: [:create, :destroy]
  end

  delete 'post_c/:id', to: 'post_c#destroy'

  resources :post_sitter do
    resource :favorite_sitters, only: [:create, :destroy]
  end

  delete 'post_sitter/:id', to: 'post_sitter#destroy'

  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  get "show_additionally", to: "rooms#show_additionally"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'
end

app/models/user.rb
class User < ApplicationRecord
  #devise設定
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { maximum: 15 }
  
  #image読み込み
  mount_uploader :image, ImageUploader
  
  #投稿
  has_many :post_cs, dependent: :destroy
  has_many :post_sitters, dependent: :destroy

  #レビュー
  has_many :reviews, dependent: :destroy

  #お気に入り
  has_many :favorite_cs, dependent: :destroy
  has_many :favorite_sitters, dependent: :destroy

  #メッセージ
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, foreign_key: :user_id

  #通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  #フォロー
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  #ゲストログイン
  def self .guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.username = 'ゲストユーザー'
      user.password = SecureRandom.urlsafe_base64
      user.profile = 'ゲストユーザーです！よろしくおねがいします'
    end
  end

  #ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  #ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  #フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません'
    end
  end

  protected
    def after_update_path_for(resource)
      user_path(resource)
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  
  def show
    @user = User.find(params[:id])
    
    #レビュー
    @reviews = Review.where(reviewee_id: @user.id)
    if @reviews.blank?
      @average_review = 0
    else
      @average_review = @reviews.average(:rate).to_f.round(1)
    end

    #メッセージ
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      
      unless @isRoom 
        @room = Room.new
        @entry = Entry.new
      end
    end

    #お気に入り
    favorite_cs = @user.favorite_cs.pluck(:post_c_id)
    @favorite_cs = PostC.where(id: favorite_cs)
    favorite_sitters = @user.favorite_sitters.pluck(:post_sitter_id)
    @favorite_sitters = PostSitter.where(id: favorite_sitters)
  end
  
  def edit
    @user = User.find(params[:id])
    @user.save
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "プロフィールの編集に成功しました！！"
    else
      flash[:alert] = "プロフィールの編集に失敗しました！！"
      render :edit
    end
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :image, :remove_image, :profile)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "users-bt" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_message_button.html.erb
<div class="contact-btn-col">
  <% unless @user == current_user %>
    <% if @isRoom == true %> <!--すでにroomがあったら「メッセージへ」と表示してメッセージに飛ばす-->
      <div class="message-button">
        <%= link_to "メッセージ", room_path(@roomId), class: "users-bt" %>
      </div>
    <% else %>
      <%= form_with model: @room, local: true do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %> <!-- entryテーブルにuser_idを送る -->
        <% end %>
        <div class="message-button">
          <%= f.submit "メッセージ", class: "users-bt", alt: "メッセージを送る" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "users-bt" %>
<% end %>

app/views/users/_user.html.erb
<div class="follow-wrap">
  <%= link_to user do %>
    <div class="row justify-content-start list-inline list-unstyled">
      <div class="icon list-inline-item">
        <% if user.image? %>
          <%= image_tag user.image.url, size: 80 %>
        <% else %>
          <%= image_tag "/assets/default.png", size: 80 %>
        <% end %>
      </div>
      <div class="list-inline-item follow-item">
        <ul>
          <li class="follow-name font-weight-bold">
            <%= user.username %>
          </li>
          <li class="follow-profile">
            <%= user.profile %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.image? %>
    <%= image_tag @user.image.url %>
  <% else %>
    <%= image_tag "/assets/default.png", :size => '160x160' %>
  <% end %>
    <button type="button" class="btn btn-outline-secondary rounded-pill">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
    </button>
  <p>
  <label>
    <%= f.check_box :remove_image %>
    Remove image
  </label>
  </p>

  <%= f.label :plofile %><br />
  <%= f.text_area :plofile, autofocus: true %>

  <%= f.submit '更新する', class: 'btn btn-primary' %>

<% end %>

app/views/users/show.html.erb
<main role="main" class="flex-shrink-0">
  <div class="users-profile-wrap">
    <div class="container hero-container">
      <div class="users-profile-hero-wrap">
        <div class="users-profile-hero-row row">      
          <div class="users-profile-main-image text-center col-md-4 icon">
          <%# 投稿者画像 %>
            <% if @user.image? %>
              <%= image_tag @user.image.url, size: 160 %>
            <% else %>
              <%= image_tag "/assets/default.png", size: 160 %>
            <% end %>
          </div>

          <div class="users-summary-col col-md-4">
              <%# 投稿者名前 %>
            <div class="users-name">
              <h3 class="font-weight-bold text-dark"><%= @user.username %></h3>
            </div>

              <%# レビュー機能 %>
            <div class="users-reviews mb-1">
              <%= link_to user_reviews_path(@user) do %>
                <%= render 'reviews/average_review', review: @reviews %>
              <% end %>
            </div>

              <%# フォロー・フォロワー %>
            <div class="users-follow-wrap">
              <div class="stats">
                <%= render 'stats' %>
              </div>
            </div>
          </div>

          <div class="contact-favorite-wrap col-md-4">
              <%# トークルームボタン %>
            <%= render 'message_button' %>

              <%# フォローボタン %>
            <div class="favorite-btn-col">
              <%= render 'follow_form' if user_signed_in? %>
            </div>

            <div class="currentuser-btn-col">
              <% if @user == current_user %>
                <%= link_to 'メッセージ', rooms_path, class: "users-bt" %>
                <%= link_to '編集', edit_user_registration_path, class: "users-bt" %>
              <% end %>
            </div>
          </div>
        </div>

      </div>


        <!--タブ-->
      <div class="tab-panel">
        <ul class="tab-group">
          <li class="tab tab-A is-active">プロフィール</li>
          <li class="tab tab-B">お気に入り</li>
          <li class="tab tab-C">レビュー</li>  
        </ul>
        

        <!--タブを切り替えて表示するコンテンツ-->
        <div class="panel-group">

            <!-- プロフィール -->
          <div class="panel tab-A is-show">
            <div class="panel-title mb-5">
              <h4>プロフィール</h4>
            </div>

            <div class="users-profile">
              <%= simple_format @user.profile %>
            </div>
          </div>


            <!-- お気に入り -->
          <div class="panel tab-B">
            <div class="panel-title mb-3">
              <h4>お気に入り</h4>
            </div>

            <% if @favorite_cs.present? %>
              <div class="panel-small-title mb-5">
                <h5>シッター利用者</h5>
              </div>
              <% @favorite_cs.each do |post| %>
                <%= link_to post_c_path(post) do %>
                  <div class="panel-favorite-wrap">
                    <div class="row panel-favorite-item list-inline mb-3">
                      <div class="panel-favorite-image icon list-inline-item">
                        <% if post.user.image? %>
                          <%= image_tag post.user.image.url, size: 60 %>
                        <% else %>
                          <%= image_tag "/assets/default.png", size: 60 %>
                        <% end %>
                      </div>
                      <div class="panel-favorite-box list-inline-item">
                        <ul>
                          <li class="panel-favorite-name">
                            <%= post.user.username %>
                          </li>
                          <li class="panel-favorite-title">
                            <%= post.title %>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="panel-favorite-content">
                      <%= post.content %>
                    </div>
                  </div>
                <% end %>
                <hr>
              <% end %>
            <% end %>


            <% if @favorite_sitters.present? %>
              <div class="panel-small-title mb-5">
                <h5>シッター</h5>
              </div>
              <% @favorite_sitters.each do |post_sitter| %>
                <%= link_to post_sitter_path(post_sitter) do %>
                  <div class="panel-favorite-wrap">
                    <div class="row panel-favorite-item list-inline mb-3">
                      <div class="panel-favorite-image icon list-inline-item">
                        <% if post_sitter.user.image? %>
                          <%= image_tag post_sitter.user.image.url, size: 60 %>
                        <% else %>
                          <%= image_tag "/assets/default.png", size: 60 %>
                        <% end %>
                      </div>
                      <div class="panel-favorite-box list-inline-item">
                        <ul>
                          <li class="panel-favorite-name">
                            <%= post_sitter.user.username %>
                          </li>
                          <li class="panel-favorite-title">
                            <%= post_sitter.title %>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="panel-favorite-content">
                      <%= post_sitter.content %>
                    </div>
                  </div>
                <% end %>
                <hr>
              <% end %>
            <% end %>
          </div>


            <!-- レビュー -->
          <div class="panel tab-C">
            <div class="panel-title mb-5">
              <%= link_to user_reviews_path(@user) do %>
                <h4 class="text-gray">レビュー</h4>
              <% end %>
            </div>
            <% if @reviews.present? %>
              <% @reviews.each do |review| %>
                <div class="panel-review-wrap">
                  <div class="row panel-review-item list-inline mb-3">
                    <div class="panel-review-image icon list-inline-item">
                      <% if review.user.image? %>
                        <%= image_tag review.user.image.url, size: 60 %>
                      <% else %>
                        <%= image_tag "/assets/default.png", size: 60 %>
                      <% end %>
                    </div>
                    <div class="panel-review-box list-inline-item">
                      <ul>
                        <li class="panel-review-name">
                          <%= review.user.username %>
                        </li>
                        <li class="panel-review-position">
                          <% if review.position == 'sitter' %>
                            <%= 'シッター' %>
                          <% else %>
                            <%= 'シッター利用者' %>
                          <% end %>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="panel-review-star mb-2">
                    <%= render 'reviews/star', review: review %>
                  </div>
                  <div class="panel-review-content">
                    <%= review.content %>
                  </div>
                  <hr>
                </div>
              <% end %>
            <% end %>
          </div>


        </div>
      </div>
    </div>
  </div>
  
</main>
<script>
  $(window).on("popstate", function() {
    window.location.reload();
  })
</script>

app/views/users/show_follow.html.erb
<main role="main" class="flex-shrink-0">
  <div class="container">

      <% provide(:title, @title) %>
      <div class="justify-content-center">
          <h2 class="text-center title-color mb-5"><%= @title %></h2>
          <% if @users.any? %>
            <%= render @users %>
            
            <%= paginate @users %>
          <% end %>
      </div>

    </div>
  </div>
</main>