config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  root to: "home#index"

  #ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
    member do
      get :following, :followers
    end
    collection do
      get :favorite_cs
      get :favorite_sitters
    end
  end
  
  resources :post_c do
    resource :favorite_cs, only: [:create, :destroy]
  end

  delete 'post_c/:id', to: 'post_c#destroy'

  resources :post_sitter do
    resource :favorite_sitters, only: [:create, :destroy]
  end

  delete 'post_sitter/:id', to: 'post_sitter#destroy'

  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  get "show_additionally", to: "rooms#show_additionally"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications, only: [:index]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'
end

app/models/favorite_c.rb
class FavoriteC < ApplicationRecord
  belongs_to :user
  belongs_to :post_c
end

app/controllers/favorite_cs_controller.rb
class FavoriteCsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:create, :destroy]

  def create
    if @post.user_id != current_user.id
      @favorite_c = FavoriteC.create(user_id: current_user.id, post_c_id: @post.id)
      @post.create_notification_favorite_c!(current_user)
    end
  end

  def destroy
    @favorite_c = FavoriteC.find_by(user_id: current_user.id, post_c_id: @post.id)
    @favorite_c.destroy
  end

  private
  def set_post
    @post = PostC.find(params[:post_c_id])
  end
end

app/helpers/favorite_cs_helper.rb
module FavoriteCsHelper
end

app/views/favorite_cs/_favorite.html.erb
<div id="fav_<%= @post.id %>">
  <% if !FavoriteC.exists?(user: current_user, post_c_id: @post.id) %>
    <%= link_to post_c_favorite_cs_path(@post), method: :post, remote: true, class: "fav-btn" do %>
      <div class="fav">
        <i class="far fa-bookmark"></i>
      </div>
    <% end %>
  <% else %>
    <%= link_to post_c_favorite_cs_path(@post), method: :delete, remote: true, class: "fav-btn" do %>
      <div class="fav">
        <i class="fas fa-bookmark"></i>
      </div>
    <% end %>
  <% end %>
</div>

app/views/favorite_cs/create.js.erb
$("#fav_<%= @post.id %>").html("<%= j(render partial: 'favorite_cs/favorite', locals: { post_c: @post }) %>");

app/views/favorite_cs/destroy.js.erb
$("#fav_<%= @post.id %>").html("<%= j(render partial: 'favorite_cs/favorite', locals: { post_c: @post }) %>");